env: "local"
storage_path: "./storage/passvault.db"
secret: "test_secret"
grpc:
    port: 8081
    timeout: 4s
    retries_count: 5
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
